export const MAX_N = 10,
  MAX_M = 10;

export enum ALGORITHMS {
  DIJKSTRA = "DIJKSTRA",
  FLOYD = "FLOYD",
  KRUSKAL = "KRUSKAL",
  PRIM = "PRIM",
  BRUTE_FORCE = "BRUTE_FORCE",
  BRANCH_AND_BOUND = "BRANCH_AND_BOUND",
}

export const ALGORITHM_NAMES = {
  [ALGORITHMS.DIJKSTRA]: "Dijkstra",
  [ALGORITHMS.FLOYD]: "Floyd",
  [ALGORITHMS.KRUSKAL]: "Kruskal",
  [ALGORITHMS.PRIM]: "Prim",
  [ALGORITHMS.BRUTE_FORCE]: "Vét cạn",
  [ALGORITHMS.BRANCH_AND_BOUND]: "Nhánh cận",
};

export enum TOPICS {
  SHORTEST_PATH = "SHORTEST_PATH",
  MINIMUM_SPANNING_TREE = "MINIMUM_SPANNING_TREE",
  TSP = "TSP",
}

export const TOPIC_NAMES = {
  [TOPICS.SHORTEST_PATH]: "Đường đi ngắn nhất",
  [TOPICS.MINIMUM_SPANNING_TREE]: "Cây khung tối tiểu",
  [TOPICS.TSP]: "TSP",
};

export const ALGORITHMS_BY_TOPIC = {
  [TOPICS.SHORTEST_PATH]: [ALGORITHMS.DIJKSTRA, ALGORITHMS.FLOYD],
  [TOPICS.MINIMUM_SPANNING_TREE]: [ALGORITHMS.KRUSKAL, ALGORITHMS.PRIM],
  [TOPICS.TSP]: [ALGORITHMS.BRUTE_FORCE, ALGORITHMS.BRANCH_AND_BOUND],
};
