export enum GRAPH_TOPIC {
  SHORTEST_PATH = "STP",
  EULERIAN_PATH = "ELP",
  MINIMUM_SPANNING_TREE = "MST",
}

export enum SHORTEST_PATH_ALGO {
  DIJKSTRA = "DIJ",
  FLOYD = "FLO",
}

export enum EULERIAN_PATH_ALGO {
  HIERHOLZER = "HIE",
}

export enum MINIMUM_SPANNING_TREE_ALGO {
  KRUSKAL = "KRU",
  PRIM = "PRI",
}

export type GRAPH_ALGO =
  | SHORTEST_PATH_ALGO
  | EULERIAN_PATH_ALGO
  | MINIMUM_SPANNING_TREE_ALGO;

export const GRAPH_TOPICS = [
  GRAPH_TOPIC.SHORTEST_PATH,
  // GRAPH_TOPIC.EULERIAN_PATH,
  GRAPH_TOPIC.MINIMUM_SPANNING_TREE,
];

export const GRAPH_TOPIC_NAMES = {
  [GRAPH_TOPIC.SHORTEST_PATH]: "Đường đi ngắn nhất",
  [GRAPH_TOPIC.EULERIAN_PATH]: "Đường đi Euler",
  [GRAPH_TOPIC.MINIMUM_SPANNING_TREE]: "Cây khung tối tiểu",
};
export const GRAPH_ALGO_NAME = {
  [SHORTEST_PATH_ALGO.DIJKSTRA]: "Giải thuật Dijkstra",
  [SHORTEST_PATH_ALGO.FLOYD]: "Giải thuật Floyd",
  [EULERIAN_PATH_ALGO.HIERHOLZER]: "Giải thuật Hierholzer",
  [MINIMUM_SPANNING_TREE_ALGO.KRUSKAL]: "Giải thuật Kruskal",
  [MINIMUM_SPANNING_TREE_ALGO.PRIM]: "Giải thuật Prim",
};

export const GRAPH_TOPIC_ALGOS = {
  [GRAPH_TOPIC.SHORTEST_PATH]: [
    SHORTEST_PATH_ALGO.DIJKSTRA,
    // SHORTEST_PATH_ALGO.FLOYD,
  ],
  [GRAPH_TOPIC.EULERIAN_PATH]: [EULERIAN_PATH_ALGO.HIERHOLZER],
  [GRAPH_TOPIC.MINIMUM_SPANNING_TREE]: [
    // MINIMUM_SPANNING_TREE_ALGO.KRUSKAL,
    MINIMUM_SPANNING_TREE_ALGO.PRIM,
  ],
};

export const MAX_N = 10,
  MAX_M = 10;

export enum ALGORITHMS {
  DIJKSTRA = "DIJKSTRA",
  FLOYD = "FLOYD",
  KRUSKAL = "KRUSKAL",
  PRIM = "PRIM",
  BRUTE_FORCE = "BRUTE_FORCE",
  BRANCH_AND_BOUND = "BRANCH_AND_BOUND",
  BACKTRACKING = "BACKTRACKING",
}

export enum TOPICS {
  SHORTEST_PATH = "SHORTEST_PATH",
  MINIMUM_SPANNING_TREE = "MINIMUM_SPANNING_TREE",
  TSP = "TSP",
  GRAPH_COLORING = "GRAPH_COLORING",
}
